# Generated by Django 2.1.6 on 2019-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=300)),
                ('month', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('driving_direction', models.CharField(max_length=300)),
                ('speed_limit', models.CharField(max_length=300)),
                ('passersby', models.CharField(max_length=300)),
                ('infractions_red_light', models.CharField(max_length=300)),
            ],
        ),
    ]
